[package]
name = "pathkvs-bin"
version = "1.0.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.17", features = ["derive"] }
ctrlc = "3.4.5"
pathkvs-core = { path = "pathkvs-core" }
pathkvs-net = { path = "pathkvs-net" }
